services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db_v17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5433:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data_v17:/var/lib/postgresql/data

  app:
    container_name: nextjs_app
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data_v17:
